plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    // for cardinal components API
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":common")


    // dependency for Trinkets
    modApi compileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.3")
    modApi compileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.3")
    // dependency for EnderPack
    modImplementation "curse.maven:trinkets-341284:5173501"
    modImplementation("curse.maven:enderpack-959446:6200716")

    modImplementation("curse.maven:more-bows-and-arrows-888468:6843671")
    modImplementation("curse.maven:dis-enchanting-table-933354:6581597")
    modImplementation("curse.maven:more-beautiful-torches-860325:5263631")
    modImplementation("curse.maven:golden-foods-873866:5860674")
    modImplementation("curse.maven:automessage-868624:6661952")
    modImplementation("curse.maven:stackable-stew-and-soup-886735:5982840")
    modImplementation("curse.maven:new-shield-variants-884272:6835805")
    modImplementation("curse.maven:new-slab-variants-896385:5725924")
    modImplementation("curse.maven:animal-armor-trims-1008327:6313689")
    modImplementation("curse.maven:eat-an-omelette-859307:5875966")

    modImplementation("curse.maven:more-useful-copper-2-0-983503:7853478")
    modImplementation("curse.maven:healthy-water-921753:5980643")
    modImplementation("curse.maven:danger-close-858922:6433614")
    modImplementation("curse.maven:time-on-display-958881:5152430")
    modImplementation("curse.maven:longer-following-time-1148090:6952683")
    modImplementation("curse.maven:mob-drops-recipes-overworld-967869:5206182")
    modImplementation("curse.maven:mob-drops-recipes-nether-968546:6084953")
    modImplementation("curse.maven:mob-drops-recipes-end-968685:5135707")
    modImplementation("curse.maven:overclocked-watches-968047:6067239")

    modImplementation("curse.maven:peaceful-hunger-1034453:7108486")
    modImplementation("curse.maven:unlocked-typing-1373339:7364813")
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}
